#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Jogo.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/jbox2d_2.1.2_ds_v2.jar:$APPDIR/lib/pbox2d.jar:$APPDIR/lib/slf4j-api-1.6.4.jar:$APPDIR/lib/slf4j-nop-1.6.4.jar" Jogo "$@"
